/* eslint-disable import/no-anonymous-default-export */
export default {
    logo: "/assets/svg/logo.svg",
    card1: "/assets/images/card1.png",
    card2: "/assets/images/card2.png",
    card3: "/assets/images/card3.png",
    card4: "/assets/images/card4.png",
    card5: "/assets/images/card5.png",
    mockup: "/assets/images/mockup.png",
    mockup1: "/assets/images/mockup1.png",
    mockup2: "/assets/images/mockup2.png",
    mockup3: "/assets/images/mockup3.png",
    mockup4: "/assets/images/mockup4.png",
    stars: "/assets/images/stars.png",
    profile1: "/assets/images/review-profile-1.png",
    profile2: "/assets/images/review-profile-2.png",
    profile3: "/assets/images/review-profile-3.png",
    cLogo1: "/assets/images/cLogo1.png",
    cLogo2: "/assets/images/cLogo2.png",
    cLogo3: "/assets/images/cLogo3.png",
    cLogo4: "/assets/images/cLogo4.png",
    cLogo5: "/assets/images/cLogo5.png",
    cLogo6: "/assets/images/cLogo6.png",
    cLogo7: "/assets/images/cLogo7.png",
    cLogo8: "/assets/images/cLogo8.png",
    video1: "/assets/images/video1.mp4",
    video2: "/assets/images/video2.mp4",
    video3: "/assets/images/video3.mp4",
    video4: "/assets/images/video4.mp4",
    video5: "/assets/images/video5.mp4",
    icons: {
        android: "/assets/svg/android.svg",
        apple: "/assets/svg/apple.svg",
        barChart: "/assets/svg/bar-chart.svg",
        camera: "/assets/svg/camera.svg",
        brain: "/assets/svg/brain.svg",
        download: "/assets/svg/download.svg",
        magnifying: "/assets/svg/magnifying.svg",
        robot: "/assets/svg/robot.svg",
        tools: "/assets/svg/tools.svg",
        instagram: "/assets/svg/instagram.svg",
        tiktok: "/assets/svg/tiktok.svg",
    },
};
